### ISSUE TITLE
JupyterLab 3.0 support

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyter-videochat#12]
Currently this doesn't work with JupyterLab 3.0. It should.

**Comment by bollwyvl** [comment]
I can look at this, unless somebody else was going to?

I think a couple key things got merged upstream (like connecting to the JSON message bus) which start to make this _very_ interesting for e.g. whiteboards, broadcasting scroll/cursor position in a notebook, etc. so it probably makes sense to figure out a way to consume (and provide attribution) for the upstream code more directly.

**Comment by yuvipanda** [comment]
@bollwyvl that sounds great! Will appreciate anything you can do :) Making a JupyterLab 3.0x compatible release - even if on npm - would definitely unblock me at least :D
