### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by bollwyvl** [yuvipanda/jupyter-videochat#17]
- [x] bump versions
- [x] validate on binder
- [x] update docs
  - [x] screenshot
  - [x] badges
  - [x] changelog
- [x] tag
- [x] upload
  - [x] pypi
  - [x] npm
- [ ] postmortem
  - [ ] bump version
  - [x] validate on [binder](https://gist.github.com/bollwyvl/a49eb70e3340055ff5b9e1c9c6202a6f) 
  - [x] [start conda-forge process](https://github.com/conda-forge/staged-recipes/pull/13847) 
  - [ ] fix CHANGELOG version link
  - [ ] update release procedure in CONTRIBUTING

**Comment by bollwyvl** [comment]
Gotta dip out for a while, but will probably tag `HEAD` and release when I get back.

@yuvipanda i was going to just go gung-ho and release `0.5.0`, but we can do a `0.5.0rc0` and test some stuff out if that feels better...

**Comment by bollwyvl** [comment]
Welp, turns out I don't have creds to push to pypi, anyway...

**Comment by yuvipanda** [comment]
@bollwyvl i invited you on PyPI. Feel free to just tag 0.5. We can always bump up

**Comment by bollwyvl** [comment]
Wicked.

https://pypi.org/project/jupyter-videochat/0.5.0/

I can't push the npm tarball, which isn't wrecking anybody's day yet, but should do it to close this out... I can _taste_ collaborative whiteboards with [ipydrawio](https://pypi.org/project/ipydrawio) :yum:

**Comment by bollwyvl** [comment]
j/k apparently it went through:

https://www.npmjs.com/package/jupyterlab-videochat/v/0.5.0

**Comment by bollwyvl** [comment]
Gah, I missed the `provides` to actually _expose_ manager to other plugins. Seems like a bit of a typescript fail, but there you go. I'll work something up, which will bump the versions, etc. and close this out.
