### ISSUE TITLE
Unable to reduce width of jitsi window

### ISSUE THREAD

**Issue by costrouc** [yuvipanda/jupyter-videochat#2]
Jitsi windows seems to easily be able to grow in width but does not respond to minimizing the window.

**Comment by goanpeca** [comment]
It also seems the mouse up event is not connected to letting go the divider on resize. After trying to resize, the pointer seems to be glued to the divider and keeps resizing the pane.

**Comment by yuvipanda** [comment]
Yeah, I saw that too. It seemed too deep in JupyterLab internals for me to do anything about though... :(

**Comment by bollwyvl** [comment]
There is some magic CSS that can be applied to iframes to avoid the drag stuff:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/style/iframe.css#L15-L32

i'll take a quick look...
