### ISSUE TITLE
Add lab router link?

### ISSUE THREAD

**Issue by bollwyvl** [yuvipanda/jupyter-videochat#7]
It would be cool to be able to support links like:

```
https://mybinder.org/v2/gh/yuvipanda/jupyter-videochat/master?urlpath=lab/chat/{:room-name}[/{:file}]
```

That would:
- do the normal binder thing
- open the named chat
- (optionally) open a file

This would make sending out a link to join a follow-along-at-home demo a one-click kind of thing.

**Comment by yuvipanda** [comment]
That sounds awesome! Would definitely be great to add.

**Comment by yuvipanda** [comment]
Instead of ':file' it would be nice if it could just use other 'lab paths', so you could do 'lab/tree/something' for example.

**Comment by bollwyvl** [comment]
hm... that would be some dark magic indeed. It looks like the [router](https://github.com/jupyterlab/jupyterlab/blob/v2.1.5/packages/application/src/router.ts#L131) will only parse the `window.location` and can't be used to arbitrarily go someplace else, e.g. `router.route(restOfUrl)`.

It mostly leaves the `?` params alone (though the double-escaping makes them hard to read). So the chat router could be out-of-band, e.g. 
```
?urlpath=lab/tree/foo.ipynb%3Fjupyter-videochat%3Dmy-chat
```
and just handle itself a little later...

**Comment by yuvipanda** [comment]
Yeah, i like that.

**Comment by bollwyvl** [comment]
So I started on the URL router here:

https://github.com/bollwyvl/jupyter-videochat/tree/add-url-router

..but it devolved into a nest of fiesty yaks, and not yet PR material:
- move things out of the react layer
  - i tried some OO react stuff, but got tired of fighting
  - so ended up with a manager exported by the plugin, like most of the jupyterlab core extensions
- hoisted some types, added a few typings
- ... and added a URL router :cry: 

So I'd probably have to do each of those in order.

The big win, though, is having the `JitsiMeetAPI` hoisted up to the plugin level, it will suddenly be very easy to extend... thinking this (or other extensions) could offer stuff like the breakout rooms (#5) or an alternative chat which supported markdown + math (a la [jupyterlab-dat](https://github.com/deathbeds/jupyterlab-dat/tree/master/packages/jupyterlab-dat-chat)).
